- name: Uninstall snapd
  become: yes
  apt:
    name: snapd
    state: absent
    purge: yes

- name: Hold snapd
  become: yes
  dpkg_selections:
    name: snapd
    selection: hold

- name: Remove snap cache
  become: yes
  file:
    path: /var/cache/snapd
    state: absent
