version: "3"
services:
  traefik:
    image: traefik:2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - 8080:8080
      - 80:80
    restart: unless-stopped
