- name: Install openssh-server
  become: yes
  apt:
    name: openssh-server
    state: present
  register: openssh_install

- name: Remove existing host keys
  become: yes
  file:
    path: '/etc/ssh/{{ item }}'
    state: absent
  with_items:
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
    - ssh_host_ed25519_key
    - ssh_host_ed25519_key.pub
    - ssh_host_rsa_key
    - ssh_host_rsa_key.pub
  when: openssh_install.changed

- name: Generate host keys
  become: yes
  openssh_keypair:
    path: /etc/ssh/ssh_host_rsa_key
    type: rsa
    size: 4096
    # state: present
    # owner: root
    # group: root
  when: openssh_install.changed

- name: Copy sshd_config
  become: yes
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
