version: "3.5"
services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID={{ docker_user.id }}
      - USER_GID={{ docker_user.gid }}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/gitea/data:/data
    ports:
      - 3000:3000
    networks:
      - default
      - gitea
    depends_on:
      - db

  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - /opt/gitea/db_data:/var/lib/postgresql/data
    networks:
      - gitea
networks:
  default:
    name: nginx-proxy-manager
    external: true
  gitea:
    name: gitea
