- name: Copy Netplan config
  become: yes
  copy:
    src: 01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
  register: config_file

- name: Remove installer Netplan config
  become: yes
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  register: installer_config_file

- name: Apply Netplan configuration
  become: yes
  command: netplan apply
  when: (config_file.changed) or (installer_config_file.changed)
