version: "3.5"
services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      - PUID={{ docker_user.id }}
      - GUID={{ docker_user.id }}
    volumes:
      - /opt/unifi-controller/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 8443:8443
    #   - 1900:1900/udp #optional
    #   - 8843:8843 #optional
    #   - 8880:8880 #optional
    #   - 6789:6789 #optional
    #   - 5514:5514/udp #optional
networks:
  default:
    name: nginx-proxy-manager
    external: true
