- name: Make adduser create private home directories by default
  # This won't be needed anymore after upgrading to Ubuntu 21.04 or above
  # See https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04
  become: yes
  replace:
    path: /etc/adduser.conf
    regexp: '^DIR_MODE=0755$'
    replace: 'DIR_MODE=0750'


- name: Check if useradd creates private home directories by default
  # This won't be needed anymore after upgrading to Ubuntu 21.04 or above
  # See https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04
  lineinfile:
    path: /etc/login.defs
    regexp: "^HOME_MODE 0750$"
    state: absent
  check_mode: yes
  changed_when: false
  register: check_useradd_home_mode

- name: Make useradd create private home directories by default
  # This won't be needed anymore after upgrading to Ubuntu 21.04 or above
  # See https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04
  become: yes
  lineinfile:
    path: /etc/login.defs
    line: "HOME_MODE 0750"
    state: present
  when: check_useradd_home_mode.found == 0

- name: Create andrew user
  become: yes
  user:
    name: andrew
    state: present
    create_home: yes

- name: Make home directory of user andrew private
  # This won't be needed anymore after upgrading to Ubuntu 21.04 or above
  # See https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04
  file:
    path: /home/andrew
    mode: '0750'

- name: Create .ssh directory for user andrew
  become: yes
  file:
    path: /home/andrew/.ssh
    state: directory
    owner: andrew
    group: andrew
    mode: '0700'

- name: Copy authorized_keys for user andrew
  become: yes
  copy:
    src: andrew_authorized_keys
    dest: /home/andrew/.ssh/authorized_keys
    owner: andrew
    group: andrew
    mode: '0644'

- name: Create ansible user
  become: yes
  user:
    name: ansible
    state: present
    create_home: yes
    password_lock: yes

- name: Create .ssh directory for user ansible
  become: yes
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0600'

- name: Copy authorized_keys for user ansible
  become: yes
  copy:
    src: ansible_authorized_keys
    dest: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: '0644'
