default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - {{ nginx_proxy_manager_ip }}

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
