version: "3.5"
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - /opt/home-assistant/config:/config
networks:
  default:
    external:
      name: nginx-proxy-manager

# TODO: Copy configuration.yaml
# This should contain the required configuration to allow for reverse proxy
