- name: Create freshrss directory
  become: yes
  file:
    path: /opt/freshrss
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install freshrss compose file
  become: true
  template:
    src: files/freshrss/docker-compose.yml
    dest: /opt/freshrss/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file

- name: Restart freshrss
  become: yes
  shell:
    chdir: /opt/freshrss
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
