- name: Create gitea directory
  become: yes
  file:
    path: /opt/gitea
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install gitea compose file
  become: true
  template:
    src: files/gitea/docker-compose.yml
    dest: /opt/gitea/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file

- name: Restart gitea
  become: yes
  shell:
    chdir: /opt/gitea
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
