- name: Install Docker
  become: yes
  apt:
    name: docker.io
    state: present

- name: Install docker-compose
  become: yes
  apt:
    name: docker-compose
    state: present

- name: Start and Enable docker.service
  become: yes
  systemd:
    name: docker.service
    state: started
    enabled: True

- name: Create group {{ docker_user.name }}
  become: yes
  group:
    name: "{{ docker_user.name }}"
    gid: "{{ docker_user.gid }}"

- name: Create user {{ docker_user.name }}
  become: yes
  user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"
    group: "{{ docker_user.name }}"
    state: present
    shell: /usr/sbin/nologin
    create_home: no
    password_lock: yes
    system: yes

- name: Install Nginx Proxy Manager
  include_tasks: nginx-proxy-manager.yml

- name: Install syncthing
  include_tasks: syncthing.yml

- name: Install mosquitto
  include_tasks: mosquitto.yml

- name: Install Home Assistant
  include_tasks: home-assistant.yml

- name: Install Unifi Controller
  include_tasks: unifi-controller.yml

- name: Install Nextcloud
  include_tasks: nextcloud.yml

- name: Install Gitea
  include_tasks: gitea.yml
