- name: Create syncthing directory
  become: yes
  file:
    path: /opt/syncthing
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install syncthing compose file
  become: true
  template:
    src: files/syncthing/docker-compose.yml
    dest: /opt/syncthing/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file

- name: Restart syncthing
  become: yes
  shell:
    chdir: /opt/syncthing
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
