- name: Create unifi-controller directory
  become: yes
  file:
    path: /opt/unifi-controller
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"

- name: Install unifi-controller compose file
  become: yes
  template:
    src: files/unifi-controller/docker-compose.yml
    dest: /opt/unifi-controller/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file

- name: restart unifi-controller
  become: yes
  shell:
    chdir: /opt/unifi-controller
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
